//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace getMotherDetails.GVK_ChildDetails {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="_102IntegrationSoap", Namespace="http://tempuri.org/")]
    public partial class _102Integration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_RegistrationDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ANCDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PregancyDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ChildDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_SyncDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostEventDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public _102Integration() {
            this.Url = global::getMotherDetails.Properties.Settings.Default.getMotherDetails_GVK_ChildDetails__102Integration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_RegistrationDetailsCompletedEventHandler Get_RegistrationDetailsCompleted;
        
        /// <remarks/>
        public event Get_ANCDetailsCompletedEventHandler Get_ANCDetailsCompleted;
        
        /// <remarks/>
        public event Get_PregancyDetailsCompletedEventHandler Get_PregancyDetailsCompleted;
        
        /// <remarks/>
        public event Get_ChildDetailsCompletedEventHandler Get_ChildDetailsCompleted;
        
        /// <remarks/>
        public event Update_SyncDetailsCompletedEventHandler Update_SyncDetailsCompleted;
        
        /// <remarks/>
        public event PostEventDetailsCompletedEventHandler PostEventDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_RegistrationDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_RegistrationDetails(string userid, string password) {
            object[] results = this.Invoke("Get_RegistrationDetails", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_RegistrationDetailsAsync(string userid, string password) {
            this.Get_RegistrationDetailsAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void Get_RegistrationDetailsAsync(string userid, string password, object userState) {
            if ((this.Get_RegistrationDetailsOperationCompleted == null)) {
                this.Get_RegistrationDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_RegistrationDetailsOperationCompleted);
            }
            this.InvokeAsync("Get_RegistrationDetails", new object[] {
                        userid,
                        password}, this.Get_RegistrationDetailsOperationCompleted, userState);
        }
        
        private void OnGet_RegistrationDetailsOperationCompleted(object arg) {
            if ((this.Get_RegistrationDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_RegistrationDetailsCompleted(this, new Get_RegistrationDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ANCDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_ANCDetails(string userid, string password) {
            object[] results = this.Invoke("Get_ANCDetails", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ANCDetailsAsync(string userid, string password) {
            this.Get_ANCDetailsAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void Get_ANCDetailsAsync(string userid, string password, object userState) {
            if ((this.Get_ANCDetailsOperationCompleted == null)) {
                this.Get_ANCDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ANCDetailsOperationCompleted);
            }
            this.InvokeAsync("Get_ANCDetails", new object[] {
                        userid,
                        password}, this.Get_ANCDetailsOperationCompleted, userState);
        }
        
        private void OnGet_ANCDetailsOperationCompleted(object arg) {
            if ((this.Get_ANCDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ANCDetailsCompleted(this, new Get_ANCDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_PregancyDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_PregancyDetails(string userid, string password) {
            object[] results = this.Invoke("Get_PregancyDetails", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_PregancyDetailsAsync(string userid, string password) {
            this.Get_PregancyDetailsAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void Get_PregancyDetailsAsync(string userid, string password, object userState) {
            if ((this.Get_PregancyDetailsOperationCompleted == null)) {
                this.Get_PregancyDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PregancyDetailsOperationCompleted);
            }
            this.InvokeAsync("Get_PregancyDetails", new object[] {
                        userid,
                        password}, this.Get_PregancyDetailsOperationCompleted, userState);
        }
        
        private void OnGet_PregancyDetailsOperationCompleted(object arg) {
            if ((this.Get_PregancyDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PregancyDetailsCompleted(this, new Get_PregancyDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ChildDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_ChildDetails(string userid, string password) {
            object[] results = this.Invoke("Get_ChildDetails", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ChildDetailsAsync(string userid, string password) {
            this.Get_ChildDetailsAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void Get_ChildDetailsAsync(string userid, string password, object userState) {
            if ((this.Get_ChildDetailsOperationCompleted == null)) {
                this.Get_ChildDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ChildDetailsOperationCompleted);
            }
            this.InvokeAsync("Get_ChildDetails", new object[] {
                        userid,
                        password}, this.Get_ChildDetailsOperationCompleted, userState);
        }
        
        private void OnGet_ChildDetailsOperationCompleted(object arg) {
            if ((this.Get_ChildDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ChildDetailsCompleted(this, new Get_ChildDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_SyncDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update_SyncDetails(string userid, string password, string BatchID, string Synchdate, string Response) {
            object[] results = this.Invoke("Update_SyncDetails", new object[] {
                        userid,
                        password,
                        BatchID,
                        Synchdate,
                        Response});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Update_SyncDetailsAsync(string userid, string password, string BatchID, string Synchdate, string Response) {
            this.Update_SyncDetailsAsync(userid, password, BatchID, Synchdate, Response, null);
        }
        
        /// <remarks/>
        public void Update_SyncDetailsAsync(string userid, string password, string BatchID, string Synchdate, string Response, object userState) {
            if ((this.Update_SyncDetailsOperationCompleted == null)) {
                this.Update_SyncDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_SyncDetailsOperationCompleted);
            }
            this.InvokeAsync("Update_SyncDetails", new object[] {
                        userid,
                        password,
                        BatchID,
                        Synchdate,
                        Response}, this.Update_SyncDetailsOperationCompleted, userState);
        }
        
        private void OnUpdate_SyncDetailsOperationCompleted(object arg) {
            if ((this.Update_SyncDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_SyncDetailsCompleted(this, new Update_SyncDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostEventDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostEventDetails(string userid, string password, long MotherID, int PregnancyID, string ChildID, int EventTypeID, int EventID, string PickupTime, string DropTime, int DistrictID, int HCID, string AdhaarFlag, string Vehicleno, int Calls, string LogUserId) {
            object[] results = this.Invoke("PostEventDetails", new object[] {
                        userid,
                        password,
                        MotherID,
                        PregnancyID,
                        ChildID,
                        EventTypeID,
                        EventID,
                        PickupTime,
                        DropTime,
                        DistrictID,
                        HCID,
                        AdhaarFlag,
                        Vehicleno,
                        Calls,
                        LogUserId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PostEventDetailsAsync(string userid, string password, long MotherID, int PregnancyID, string ChildID, int EventTypeID, int EventID, string PickupTime, string DropTime, int DistrictID, int HCID, string AdhaarFlag, string Vehicleno, int Calls, string LogUserId) {
            this.PostEventDetailsAsync(userid, password, MotherID, PregnancyID, ChildID, EventTypeID, EventID, PickupTime, DropTime, DistrictID, HCID, AdhaarFlag, Vehicleno, Calls, LogUserId, null);
        }
        
        /// <remarks/>
        public void PostEventDetailsAsync(
                    string userid, 
                    string password, 
                    long MotherID, 
                    int PregnancyID, 
                    string ChildID, 
                    int EventTypeID, 
                    int EventID, 
                    string PickupTime, 
                    string DropTime, 
                    int DistrictID, 
                    int HCID, 
                    string AdhaarFlag, 
                    string Vehicleno, 
                    int Calls, 
                    string LogUserId, 
                    object userState) {
            if ((this.PostEventDetailsOperationCompleted == null)) {
                this.PostEventDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostEventDetailsOperationCompleted);
            }
            this.InvokeAsync("PostEventDetails", new object[] {
                        userid,
                        password,
                        MotherID,
                        PregnancyID,
                        ChildID,
                        EventTypeID,
                        EventID,
                        PickupTime,
                        DropTime,
                        DistrictID,
                        HCID,
                        AdhaarFlag,
                        Vehicleno,
                        Calls,
                        LogUserId}, this.PostEventDetailsOperationCompleted, userState);
        }
        
        private void OnPostEventDetailsOperationCompleted(object arg) {
            if ((this.PostEventDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostEventDetailsCompleted(this, new PostEventDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_RegistrationDetailsCompletedEventHandler(object sender, Get_RegistrationDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_RegistrationDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_RegistrationDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_ANCDetailsCompletedEventHandler(object sender, Get_ANCDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ANCDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ANCDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_PregancyDetailsCompletedEventHandler(object sender, Get_PregancyDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PregancyDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PregancyDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_ChildDetailsCompletedEventHandler(object sender, Get_ChildDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ChildDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ChildDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Update_SyncDetailsCompletedEventHandler(object sender, Update_SyncDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_SyncDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_SyncDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostEventDetailsCompletedEventHandler(object sender, PostEventDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostEventDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostEventDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591